### ISSUE TITLE
Logo Design For 3 Minutes

### ISSUE THREAD

**Issue by zularizal** [andrew-tc/3-minutes#1]
Hi,  I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. And it's free. What do you think?

**Comment by andrew-tc** [comment]
@zularizal Hi, thank you very much for your interest. First of all, I have to state that this project might just be a simple personal/hobby project that doesn't have a clear goal, but if you're okay with that, then I'm okay too :)

**Comment by zularizal** [comment]
Okay. Give me time to make it. I will upload the logo proposal in the next reply.

**Comment by zularizal** [comment]
This is my logo design for your project. What do you think? is there anything you like?

If something wants to be changed, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/47094724-f2a8c500-d255-11e8-93a4-b2c93f2f2fa2.png)

**Comment by andrew-tc** [comment]
Thank you very much, I like the concept of using "3" and clock! 👍 

As for the color, since my inspiration was based on cup noodle's 3 minutes, I think I prefer the yellow one to represent the noodle color.

Also, since the app is more "fun" in nuance, is it possible to make the logo look more casual? The proposed logo certainly looks good, but might be too formal for this :)

**Comment by zularizal** [comment]
@andrew-tc  Yes, I will try it.

Can you send the appearance of your application. Maybe this will help me to form a casual looking logo.
